export const types = {
  LOADING_PHOTOS: 'LOADING_PHOTOS',
  ERROR_PHOTOS: 'ERROR_PHOTOS',
  SUCCESS_PHOTOS: 'SUCCESS_PHOTOS',
  SET_SEARCH_VALUE: 'SET_SEARCH_VALUE',
  SAVE_IMAGE: 'SAVE_IMAGE',
  REMOVE_IMAGE: 'REMOVE_IMAGE',
  SET_NUM_IMAGES_PER_PAGE: 'SET_NUM_IMAGES_PER_PAGE'
}