export const types = {
  LOADING_PHOTOS: 'LOADING_PHOTOS',
  ERROR_PHOTOS: 'ERROR_PHOTOS',
  SUCCESS_PHOTOS: 'SUCCESS_PHOTOS',
  SET_SEARCH_VALUE: 'SET_SEARCH_VALUE',
  SAVE_IMAGE: 'SAVE_IMAGE',
  REMOVE_IMAGE: 'REMOVE_IMAGE',
  SET_NUM_IMAGES_PER_PAGE: 'SET_NUM_IMAGES_PER_PAGE',
  
  REGISTERING_NEW_USER: 'REGISTER_NEW_USER',
  NEW_USER_REGISTERED: 'NEW_USER_REGISTERED',
  LOG_ERROR_REGISTER_NEW_USER: 'ERROR_REGISTER_NEW_USER',
  LOGGING_IN: 'LOGGING_IN',
  LOGGING_IN_ERROR: 'LOGGING_IN_ERROR',
  SIGNED_IN: 'SIGNED_IN',
  SET_USER_STATUS: 'USER_STATUS',
  LOGOUT: 'LOGOUT',

}